AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    lambda-authorizer-basic-auth

    SAM Template for lambda-authorizer-basic-auth
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3


Resources:

    LambdaAuthorizerBasicAuthFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: lambda_authorizer_basic_auth/
            Handler: app.lambda_handler
            Runtime: python3.9
            Tracing: Active
            Policies:
                - DynamoDBReadPolicy:
                    TableName: !Ref LambdaAuthorizerBasicAuthUserTable 
            Environment:
                Variables:
                    TABLE_NAME: lambda-authorizer-basic-auth-users
                    LOG_LEVEL: INFO

    LambdaAuthorizerBasicAuthUserTable:
        Type: AWS::Serverless::SimpleTable
        Properties:
            TableName: lambda-authorizer-basic-auth-users
            PrimaryKey:
                Name: username
                Type: String
            SSESpecification:
                SSEEnabled: true

Outputs:

    LambdaAuthorizerBasicAuthFunction:
      Description: "Lambda Authorizer Basic Auth Function ARN"
      Value: !GetAtt LambdaAuthorizerBasicAuthFunction.Arn
